--
-- Table structure for table `emr_cluster_metadata`
--
CREATE TABLE IF NOT EXISTS `emr_cluster_metadata` (
  `metadata_id` int(11) NOT NULL AUTO_INCREMENT,
  `cluster_id` varchar(45) DEFAULT NULL,
  `cluster_name` varchar(128) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `status` varchar(45) DEFAULT NULL,
  `master_ip` varchar(45) DEFAULT NULL,
  `rm_url` varchar(128) DEFAULT NULL,
  `message` text,
  `api_request_id` varchar(45) DEFAULT NULL,
  `lambda_request_id` varchar(45) DEFAULT NULL,
  `status_code` varchar(20) DEFAULT NULL,
  `last_updated_timestamp` datetime DEFAULT NULL,
  `creation_request_timestamp` datetime DEFAULT NULL,
  `do_terminate` tinyint(1) DEFAULT '0',
  `cluster_details` text,
  `created_by` varchar(128) DEFAULT NULL,
  `last_updated_by` varchar(55) DEFAULT NULL,
  `account` varchar(45) DEFAULT NULL,
  `headless_users` varchar(500) DEFAULT NULL,
  `segment` varchar(45) DEFAULT NULL,
  `dns_name` varchar(500) DEFAULT NULL,
  `dns_flip` tinyint(1) DEFAULT '0',
  `is_prod` tinyint(1) DEFAULT '0',
  `dns_flip_completed` tinyint(1) DEFAULT '0',
  `original_cluster_id` varchar(50) DEFAULT NULL,
  `request_ticket` varchar(45) DEFAULT NULL,
  `new_cluster_id` varchar(200) DEFAULT NULL,
  `ami_rotation_days_togo` int(11) DEFAULT '0',
  `auto_ami_rotation` tinyint(1) DEFAULT '0',
  `autopilot_window_start` int(11) DEFAULT '0',
  `autopilot_window_end` int(11) DEFAULT '24',
  `ami_rotation_sla_days` int(11) DEFAULT '30',
  `autoscaling_instance_group` varchar(45) DEFAULT NULL,
  `autoscaling_min` int(11) DEFAULT '0',
  `autoscaling_max` int(11) DEFAULT '0',
  PRIMARY KEY (`metadata_id`)
);
