INSERT INTO `configuration_definitions` (`id`, `config_name`, `config_description`, `config_type`, `data_type`, `encryption_required`, `is_mandatory`, `is_user_accessible`) VALUES
(1,'add_steps_to_clusters_scheduler','Add steps to new clusters scheduler',1,3,0,1,0),
(2,'add_step_notifications','Sends email to user who created new step in a cluster',1,3,0,0,0),
(3,'autoscaling_config_test_scheduler','Auto scaling config is verified between servless and test criteria',1,3,0,0,0),
(4,'auto_ami_rotate_scheduler','This will allow rotation of AMI in the background',1,3,0,1,0),
(5,'check_cluster_status_with_termination_initiated_scheduler','Change the status of clusters to terminated if they were pending termination.',1,3,0,1,0),
(6,'collect_cluster_metrics_scheduler','Scheduler will collect cluster metrics from resource manager',1,3,0,1,0),
(7,'connectivity_test_scheduler','This scheduler will perform connectivity on EMR',1,3,0,0,0),
(8,'create_cluster_notifications','Sends out create cluster email notifications',1,3,0,0,0),
(9,'daily_report_scheduler','Generate daily AMI and cluster usage report',1,3,0,0,0),
(10,'dns_flip_notifications','Sends out email notification on DNS flip event',1,3,0,0,0),
(11,'gateway_api_key','Gateway API key to connect with backend',2,1,0,1,0),
(12,'monthly_report_scheduler','Generate monthly cluster usage report',1,3,0,0,0),
(13,'rds_cleanup_scheduler','Cleans up terminated cluster metadata after six months',1,3,0,0,0),
(14,'rotate_ami_notifications','Sends out email notification on rotate AMI event',1,3,0,0,0),
(15,'segment_reports_scheduler','Sends out segment reports to segment leaders',1,3,0,0,0),
(16,'sso_email_key','SSO email key',1,1,0,0,0),
(17,'sso_qbn_authid','SSO authentication id',1,1,0,0,0),
(18,'sso_qbn_ptc_authid','SSO ptc authentication id',1,1,0,0,0),
(19,'sso_qbn_ptc_tkt','SSO ptc ticket',1,1,0,0,0),
(20,'sso_qbn_tkt','SSO ticket',1,1,0,0,0),
(21,'sso_shared_key','SSO key for decrypting SSO data',1,1,0,0,0),
(22,'subscription_reports_scheduler','Scheduler to send out subscribed cluster reports',1,3,0,0,0),
(23,'terminate_cluster_notifications','Sends out email notification on cluster termination event',1,3,0,0,0),
(24,'terminate_completed_clusters_scheduler','Enables auto termination of cluster',1,3,0,1,0),
(25,'testsuites_enabled','Enables or disables test suites at account level',2,3,0,0,0),
(26,'test_cluster_ttl','Value to specify duration after which test clusters will be terminated',1,2,0,0,0),
(27,'validate_cluster_steps_scheduler','Update the status of steps once they are submitted',1,3,0,1,0),
(28,'validate_existing_clusters_scheduler','Update the status of exiting running cluster',1,3,0,1,0),
(29,'validate_new_clusters_scheduler','Update the status of cluster once the cluster is initiated',1,3,0,1,0),
(30,'verify_number_of_bootstraps_scheduler','Verify the number of bootstraps between backend and application',1,3,0,0,0),
(31,'verify_number_of_default_steps_scheduler','Verify the number of default steps between backend and application',1,3,0,0,0),
(32,'weekly_report_scheduler','Generate weekly cluster usage report',1,3,0,0,0),
(33,'from_email_address','From email address used by application to send out emails',1,1,0,0,0),
(34,'jira_enabled_global','Global switch to turn on/off JIRA validation',1,3,0,0,1),
(35,'jira_enabled_account','Allows JIRA validation for the account. Requires JIRA username, password and url',2,3,0,1,1),
(36,'test_cluster_auto_termination','Allows auto termination of test clusters',2,3,0,0,0),
(37,'collect_cluster_costs','Collects cost of the cluster from AWS cost explorer',1,3,0,1,0),
(38,'gateway_api_url','URL for connecting to backend ',2,1,0,1,0),
(39,'report_recipients','Email receipents for all reports',1,1,0,0,0),
(40,'servicenow_enabled_global','Global flag to turn on/off service now validation',1,3,0,0,1),
(41,'servicenow_enabled_account','Turns on/off service now validation',2,3,0,1,1),
(42,'sso_url','SSO URL',1,1,0,0,0),
(43,'sso_redirect_url','SSO redirect URL',1,1,0,0,0),
(44,'jira_projects','List of(comma separated) JIRA project names',2,1,0,0,0),
(45,'jira_user','Username to connect with JIRA services',2,1,0,0,0),
(46,'jira_password','Password to connect with JIRA services',2,1,1,0,0),
(47,'jira_url','URL to connect with JIRA services',2,1,0,0,0),
(48,'servicenow_user','Username to connect with Servicenow services',2,1,0,0,0),
(49,'servicenow_password','Password to connect with Servicenow services',2,1,1,0,0),
(50,'servicenow_url','URL to connect with Servicenow services',2,1,0,0,0),
(51,'notification_recipients','Email of recepients for cluster notifications',1,1,0,0,0),
(52,'sso_enabled','Global switch to turn on/off SSO functionality',1,3,0,0,1);
