INSERT INTO `emr_billing_component_cost_hist` (`emr_name`, `emr_cost`, `created_date`) VALUES
('exploratory-sales',700, CURRENT_TIMESTAMP()),
('scheduled-sales',1000, CURRENT_TIMESTAMP()),
('exploratory-sales-test1',500, CURRENT_TIMESTAMP()),
('exploratory-sales',700, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -1 DAY)),
('scheduled-sales',1000, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -1 DAY)),
('exploratory-sales-test1',500, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -1 DAY)),
('exploratory-sales',700, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -2 DAY)),
('scheduled-sales',1000, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -2 DAY)),
('exploratory-sales-test1',500, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -2 DAY)),
('exploratory-sales',700, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -3 DAY)),
('scheduled-sales',1000, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -3 DAY)),
('exploratory-sales-test1',500, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -3 DAY)),
('exploratory-sales',700, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -4 DAY)),
('scheduled-sales',1000, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -4 DAY)),
('exploratory-sales-test1',500,DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -4 DAY)),
('exploratory-sales',700, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -5 DAY)),
('scheduled-sales',1000, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -5 DAY)),
('exploratory-sales-test1',500, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -5 DAY)),
('exploratory-sales',700, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -6 DAY)),
('scheduled-sales',1000, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -6 DAY)),
('exploratory-sales-test1',500, DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL -6 DAY));
