const EMRCostActionTypes = {
    EMRCOST_STATUS_FETCHING: 'EMRCOST_STATUS_FETCHING',
    EMRCOST_STATUS_SUCCESS: 'EMRCOST_STATUS_SUCCESS',
    EMRCOST_STATUS_ERROR: 'EMRCOST_STATUS_ERROR',
    GET_CLUSTER_COST_MONTHLY_FETCHING:'GET_CLUSTER_COST_MONTHLY_FETCHING',
    GET_CLUSTER_COST_MONTHLY_SUCCESS:'GET_CLUSTER_COST_MONTHLY_SUCCESS',
    GET_CLUSTER_COST_MONTHLY_ERROR:'GET_CLUSTER_COST_MONTHLY_ERROR',
    GET_CLUSTER_COST_WEEKLY_FETCHING:'GET_CLUSTER_COST_WEEKLY_FETCHING',
    GET_CLUSTER_COST_WEEKLY_SUCCESS:'GET_CLUSTER_COST_WEEKLY_SUCCESS',
    GET_CLUSTER_COST_WEEKLY_ERROR:'GET_CLUSTER_COST_WEEKLY_ERROR',
    GET_CLUSTER_COST_CUSTOM_FETCHING:'GET_CLUSTER_COST_CUSTOM_FETCHING',
    GET_CLUSTER_COST_CUSTOM_SUCCESS:'GET_CLUSTER_COST_CUSTOM_SUCCESS',
    GET_CLUSTER_COST_CUSTOM_ERROR:'GET_CLUSTER_COST_CUSTOM_ERROR'
};

export default EMRCostActionTypes;