const ProfileActionTypes = {
    GET_SUBSCRIPTIONS_FETCHING: 'GET_SUBSCRIPTIONS_FETCHING',
    GET_SUBSCRIPTIONS_ERROR: 'GET_SUBSCRIPTIONS_ERROR',
    GET_SUBSCRIPTIONS_SUCCESS: 'GET_SUBSCRIPTIONS_SUCCESS',
    UPDATE_SUBSCRIPTIONS_ERROR: 'UPDATE_SUBSCRIPTIONS_ERROR',
    UPDATE_SUBSCRIPTIONS_SUCCESS: 'UPDATE_SUBSCRIPTIONS_SUCCESS',
    CLEAR_UPDATES: 'CLEAR_UPDATES'
}

export default ProfileActionTypes;