const UserActionTypes = {
    SIGN_IN_FETCHING: 'SIGN_IN_FETCHING',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',
    SIGN_OUT: 'SIGN_OUT',
    CLEAR_SIGN_IN_ERROR: 'CLEAR_SIGN_IN_ERROR',
    AUTHENTICATE_USER_FETCHING: 'AUTHENTICATE_USER_FETCHING',
    AUTHENTICATE_USER_SUCCESS: 'AUTHENTICATE_USER_SUCCESS',
    AUTHENTICATE_USER_ERROR: 'AUTHENTICATE_USER_ERROR'
};

export default UserActionTypes;